# Generated by Django 3.1.2 on 2020-10-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201013_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/upload/%Y/%m/%d/'),
        ),
    ]
