# Generated by Django 3.1.2 on 2021-05-05 02:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201013_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resume',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='hi'),
            preserve_default=False,
        ),
    ]
